---
description: Pipeline for Windows Powershell events
processors:
 - set:
      field: ecs.version
      value: '1.12.0'
on_failure:
  - set:
      field: "error.message"
      value: "{{ _ingest.on_failure_message }}"
